puppetlabs/education-builds

modules/classroom/manifests/agent/time.pp

https://tickets.puppetlabs.com/browse/COURSES-670

Added selector to set service_name for ntp

---

modules/classroom/manifests/agent/git.pp
modules/classroom/metadata.json

This also fixes some missing commas in metadata.json

Added default git path

---

modules/training/manifests/init.pp

Just saw it's in training too :+1:

Another wget issue

---

modules/classroom/manifests/console/user.pp
modules/classroom/metadata.json
modules/rbac/LICENSE
modules/rbac/README.md
modules/rbac/lib/puppet/provider/rbac_api.rb
modules/rbac/lib/puppet/provider/rbac_user/ruby.rb
modules/rbac/lib/puppet/type/rbac_user.rb
modules/rbac/metadata.json
modules/rbac/tests/users.pp

Yay, API based management. This means not running 74 rake tasks every
time the Master's agent runs.
Next up is the class parameters.
See https://forge.puppetlabs.com/pltraining/rbac/readme

First working release of the RBAC module

---

modules/userprefs/files/vim/vim/ftplugin/puppet.vim
modules/userprefs/files/vim/vim/syntax/puppet.vim

Pulled in some of the previous settings for vim.  It looks like autoindent was not working in the latest.

Userprefs vim

---

Rakefile.new
manifests/site.pp
modules/bootstrap/templates/rc.local.erb
modules/student/manifests/init.pp
packer/educationbase.json
packer/http/ks-student.cfg
packer/http/ks-training.cfg
packer/scripts/student_build.sh
packer/scripts/student_cleanup.sh
packer/scripts/student_skytap_build.sh
packer/scripts/student_skytap_cleanup.sh
packer/scripts/training_skytap_build.sh
packer/scripts/training_skytap_cleanup.sh
packer/student.json
packer/student_skytap.json
packer/training_skytap.json
packer/vmware.json

A minimal student VM that attempts to auto install puppet from master.puppetlabs.vm (if it resolves and puppet isn't already installed). This also adds some rake tasks and supporting scripts for skytap builds, i.e. VMs that will get their hostname from DHCP.

Minimal Student VM

---

modules/bootstrap/templates/rc.local.erb

Improvement to the login screen for all the VMs.  Displays the IP address and the default login information.

Login screen

---

modules/classroom/files/license.key

Change to field of license on request

---

README.markdown
packer/educationbase.json
packer/educationbuild.json
packer/scripts/cleanup.sh
packer/scripts/learning_build.sh
packer/scripts/pre_build.sh
packer/scripts/student_build.sh
packer/scripts/student_skytap_build.sh
packer/scripts/training_build.sh
packer/scripts/training_skytap_build.sh

This just adds a prebuild step which makes a base VM.  From that base we can more quickly iterate on VM changes by just running packer with educationbuild.json

Intermediate VM build for faster iteration

---

modules/bootstrap/manifests/cache_modules.pp

Is there a reason we weren't doing this before?  I'm not sure how offline class would work without the classroom module.

caching classroom module

---

packer/educationbuild.json
packer/training.json

This is to match the output of the automated builds

Use new naming convention, and increment version

---

manifests/site.pp

Cache the 32bit agent files so that pe_repo will work offline.

Cache 32bit files

---

scripts/classroom/setup_classroom.sh

https://tickets.puppetlabs.com/browse/TRAINVM-197

Don't let users name their VM 'student'

---

Puppetfile
Rakefile
manifests/site.pp
packer/educationbase.json
packer/educationbuild.json
packer/http/ks-puppetfactory.cfg
packer/http/ks-student.cfg
packer/puppetfactory.json

Adds a centos 7 based puppetfactory vm with PE preinstalled.
This branch also the first step toward full CentOS7 support for the Training VM.

Centos 7 & puppetfactory

---

scripts/classroom/enc_injector.rb

* this makes the architect lab less awkward
* I didn't want this on the VM because it's terrible, but the
alternative was more terrible :(

Drop this file on the VM to start with

---

manifests/post.pp

oops, I didn't give the full paths.

Full paths of files

---

scripts/classroom/setup_classroom.sh

Removing the timeout reverts it to 3000ms, which seems to be the max you can set with the -W parameter anyway.  This should help for flaky networks, or those lacking good ICMP.

Setup script

---

scripts/classroom/external_node.rb

Change enc to output yaml by default

---

scripts/classroom/setup_classroom.sh

The regex does the following: beginning of the line, one character a-z, two or more charactesr a-z or 0-9, end of the line.

Tuning hostname regex for students

---

scripts/classroom/verify_classroom.sh

Bump memory suggestions

---

scripts/classroom/hiera_explain.rb

This allows you to pass in scope arguments properly

Wasn't parsing options correctly

---

Rakefile

Running the command goes quiet after `Editing /etc/sysconfig/network`, this makes it a bit nicer with more output per steps

Adds more output for the various steps

---

Puppetfile
ReleaseNotes.md
packer/scripts/puppetfactory_build.sh
version.yaml

This is mostly a release bump.

Pf centos7

---

scripts/classroom/external_node.rb

Fix the external node script

---

cloud/virtual/skytap/humanreadable.rb

Just a simple script so give some output we can share with students.

Parse output of skytap script to be human readable

---

cloud/virtual/skytap/virtualclassroom.rb

- View only URL for instructors
- Optional debug output for troubleshooting skytap weirdness
- Checks status of REST calls rather than assuming they worked

Status checks for skytap VM provisioning

---

scripts/classroom/console_password_reset.rb

This uses the new filesystem layout, so it's not backwards compatible.

ports password reset to SG

---

scripts/classroom/setup_classroom.sh

This should not change behaviour at all, other than to remove the
extraneous question. This should not change any of the issues noticed
by Greg. But it should make it easier to track them down.

Simplified script to remove secondary agent

---

Rakefile
packer/scripts/learning_cleanup.sh

TRAINVM-241 #resolved #time 4h

Use AIO installer

---

Puppetfile

Puppet on the path

---

packer/puppetfactory.json

TRAINTECH-285 #resolved #time 5m

Bump up puppetfactory disk space

---

Puppetfile
Rakefile
ReleaseNotes.md
packer/awsbuild.json
packer/educationbuild.json
packer/scripts/student_build.sh
packer/scripts/training_build.sh
version.yaml

This uses the puppet-agent ruby/gem for the build and removes rvm, which was causing issues with the hocon gem.

Fix hocon issues

---

manifests/post.pp

TRAINVM-250 #resolved #time 1h

Run yum update before disabling repos

---

cloud/virtual/skytap/fallback.yaml
cloud/virtual/skytap/fundamentals.yaml
cloud/virtual/skytap/infrastructure.yaml
cloud/virtual/skytap/virtualclassroom.rb
cloud/virtual/skytap/windows.yaml

TRAINTECH-212 #resolved #time 2h

Skytap name

---

packer/learning.json
packer/puppetfactory.json

Just a minor version update to the iso to make it match what's currently available.

Centos7 version

---

scripts/classroom/external_node.rb

TRAINVM-180 #resolved #time 10m

Fail gracefully on empty classification

---

packer/scripts/cleanup.sh

LEARNVM-272 #resolved #time 2h

Workaround for centos7 bug

---

packer/awsbuild.json
packer/scripts/base.sh
packer/scripts/learning_build.sh

This successfully builds a Learning VM on EC2.

LEARNVM-85 #resolved #time 2h

---

packer/awsbuild.json
packer/educationbuild.json

The latest version of packer requires this.

Use PTY for builds

---

README.markdown

Just a typo fix.
Hope you're having a great day! :)

Fix a typo in README.markdown

---

packer/educationbase.json
packer/educationbuild.json
packer/learning.json
packer/scripts/base.sh
packer/scripts/cleanup.sh
packer/scripts/learning_build.sh
packer/scripts/learning_cleanup.sh
packer/scripts/master_learning_build.sh
packer/scripts/student_cleanup.sh
packer/scripts/vmtools.sh
packer/student.json

This cleans up the use of sudo in the build scripts and uses packer's built in command instead.

Remove sudo from build scripts

---

scripts/classroom/hiera_explain.rb

This will print out all the data available from Hiera, as each of the
priority levels can see them. It's currently YAML only, though it'd be
trivial to add JSON support. It cannot be part of Hiera itself without
some backend monkeypatching. :/

Updates the hiera explain script to print results

---

README.markdown

WIP link to release notes

---

scripts/classroom/reset_ssl_certificates.sh

TRAINTECH-381 #resolved #time 45m

Update the cert reset script to include app orch

---

ReleaseNotes.md

This format matches what the courseware Rakefile is looking for.

Fixed format of notes

---

cloud/aws/courses/architect.yaml
cloud/skytap/virtualclassroom.rb

Add architect AMI to the yaml file
Fixes the skytap script by adding a sleep so that the API has time to
reply.

Improvments to OILT automation

---

scripts/base.sh
scripts/cleanup.sh
scripts/export-ova.sh
scripts/time.sh
setup.sh
templates/educationbase.json
templates/educationbuild.json
templates/student.json

TRAINVM-281 #resolved #time 8h

TRAINVM-281 #resolved #time 8h

---

setup.sh

Jenkins was failing because there are spaces in the directory name.  This fixes it.

Use quotes around directory name

---

cloud/aws/README.md
cloud/aws/classroom_setup.sh
cloud/aws/ec2classroom.rb
cloud/aws/enrollment_parser.rb

These will need some polish eventually but this should make them a bit easier to use.  The new script takes the CSV from learndot and runs through an interactive dialog to generate the json file expected by ec2classroom.rb.

Interactive build scripts for setting up classrooms

---

Rakefile

Require net/http

---

cloud/aws/codes.yaml

@marrero984 should probably update others.

fixing a couple of the course codes

---

cloud/aws/courses/architect.yaml
cloud/aws/courses/default.yaml
cloud/aws/courses/infrastructure.yaml
cloud/aws/courses/puppetfactory.yaml
cloud/aws/courses/windows.yaml
templates/awsbuild.json

The builds were broken on AWS, looks like it wasn't install puppet.

Do the full build for AMIs

---

cloud/skytap/virtualclassroom.rb

http://help.skytap.com/API_Documentation.html#Enabledisableautosuspend

disable autosuspend of vms

---

build_files/Puppetfile
build_files/Rakefile
cloud/libvirt/courses/vms/master.xml.erb
cloud/libvirt/courses/vms/windows.xml.erb
cloud/libvirt/courses/volumes/windows.xml.erb
cloud/libvirt/courses/windows.yaml
scripts/ciab_build.sh
scripts/ciab_cleanup.sh
scripts/ciab_pre_build.sh
templates/ciab.json

Some module dependencies, a better template for windows VMs and fixing an error in the rake.

Classroom in a box

---

Rakefile
setup.sh
templates/aws_selfpaced.json

There are also a few unrelated minor fixes that haven't been merged yet.

Support linux builders

---

scripts/learning_full.sh

Build script for doing the LVM build in a single step, mostly useful for possible AMI build.

Build script for full learning VM build

---

Rakefile
build_files/version.yaml
templates/aws_selfpaced.json
templates/ciab.json
templates/educationbuild.json
templates/educationtest.json
templates/student.json

Including the version bump since this will need an immedate release.

Mac address

---

build_files/Rakefile
scripts/training_build.sh
scripts/training_pre_build.sh

This also fixes an issue with the build scripts for the training VM

Cache PE on every VM except student

---

Rakefile
build_files/Puppetfile
build_files/Puppetfile.stable
build_files/Rakefile
templates/educationbuild.json

Use Puppetfile.stable to track a stable release versions of build modules.

Stable modules

---

build_files/Puppetfile.learning

LEARNVM-534 #resolved #time 2h

Add module versions that will meet postgresql deps

---

build_files/manifests/post.pp

LEARNVM-546 #resolved #time 30m

Disable docker repo in post-build

---

setup.sh

Move config setups out of jenkins job and into setup script

Jenkins setup script

---

templates/aws_selfpaced.json
templates/awsbuild.json

The build was uncomfortably close to an hour. Let's give it some headroom.

(maint) Increase AMI lifetime

---

cloud/aws/courses/architect.yaml

Alternate logins for student masters in Arch

---

Rakefile

This change corresponds to
https://github.com/puppetlabs/puppet-quest-guide/pull/230
Replace us_en with en_us to match i18n standard.

(LEARNVM-640) Replace Rakefile us_en reference with en_us

---

cloud/aws/courses/default.yaml

TRAINTECH-1483 #resolved #time 10m

Switch AMI to self-provisioned

---

cloud/aws/notes.erb

Merge after https://github.com/puppetlabs/vcmanager/pull/78 has been released

[WIP] (maint) Add link to PE Console

---

cloud/aws/notes.erb

TRAINTECH-1584 #resolved #time 10m

Only display Windows info when it exists

---

cloud/aws/notes.erb

TRIANTECH-1729 #resolved #time 10m
Fix the conditional to check if there are actually Windows nodes

(TRAINTECH-1729) Remove Unnecessary Windows Notes
