modules/student/manifests/init.pp

Otherwise you get the following:
```
--2015-01-13 20:08:11--  https://www.wordpress.org/wordpress-3.8.tar.gz
Resolving www.wordpress.org... 66.155.40.250, 66.155.40.249
Connecting to www.wordpress.org|66.155.40.250|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://wordpress.org/wordpress-3.8.tar.gz [following]
--2015-01-13 20:08:11--  https://wordpress.org/wordpress-3.8.tar.gz
Resolving wordpress.org... 66.155.40.249, 66.155.40.250
Connecting to wordpress.org|66.155.40.249|:443... connected.
ERROR: certificate common name “*.wordpress.org” doesn’t match requested host name “wordpress.org”.
To connect to wordpress.org insecurely, use ‘--no-check-certificate’.
```

Adds `--no-check-certificate` to wget

---

scripts/classroom/hiera_explain.rb

This will use the current node's facts cache and allow the user to
override on the command line, like this:
```
$ hiera_explain.rb fqdn=boo
Backend data directories:
* yaml: /etc/puppetlabs/puppet/hieradata
Expanded hierarchy:
* training.puppetlabs.vm
* boo
* defaults
File lookup order:
* /etc/puppetlabs/puppet/hieradata/training.puppetlabs.vm.yaml
* /etc/puppetlabs/puppet/hieradata/boo.yaml
* /etc/puppetlabs/puppet/hieradata/defaults.yaml
```

This adds a dinky script to describe hiera lookups

---

Rakefile
manifests/post.pp
manifests/site.pp
modules/bootstrap/manifests/init.pp
modules/classroom/manifests/repositories.pp
modules/student/manifests/init.pp

This moves the yumrepo offline classification to a second puppet manifest that's run after the initial VM bootstrap.

Bootstrap repos

---

cloud/virtual/skytap/WYFM.yaml
cloud/virtual/skytap/example.yaml
cloud/virtual/skytap/virtualclassroom.rb

Lets you add a name other than "master" for the base VM
Includes an example template for Write your first module
Fixes a bug where it'll crash if a port is already mapped on the template

Updates for WYFM course

---

Rakefile

This adds a task and methods to extract the created VM artifact
from vSphere as an OVA, then ship that OVA to 2 places:
First back into vSphere as a VM suitable for testing.
Second to a directory on the int-resources share.
The shipping tasks need to be run from a machine with
ovftool installed, and if shipping to int-resources, with
the NFS export mounted. Obviously these are intended to be
used on the internal Puppet Labs network.
In addition, there is a minor update required to the Jenkins
build job. The task that exports the VM from vmware needs to know
the name of the pooler VM used. This is accomplished in my test job
by having Beaker write out a properties file containing the name.

(re-4124) Package and ship VM artifacts

---

scripts/classroom/setup_classroom.sh

Underscores cause the classroom module to create broken environments, and are not legal characters in domain names anyway. This change just removes the underscore from the name validation regex. The regex could probably be further improved in other ways, but this will at least catch one case we know to break things.

underscores are illegal and break several things

---

manifests/post.pp

I'm going to move all of the post-build cleanup scripts to this manifest so that we're less dependent on bash scripts.

Cleaning up some files in /root

---

scripts/classroom/setup_classroom.sh

The simplified installer doesn't make this directory, but in Architect,
we need it to exist so we can populate it with a starting environment.
This uses `-p` so it becomes a noop in the case that the installer changes
to include the directory at some point.
Fixes #TRAINVM-194

Create environment directory

---

cloud/virtual/skytap/virtualclassroom.rb
cloud/virtual/skytap/windows.yaml

The lines about adding a "view_only" url are commented out because Skytap throws a 409 error.  I suspect that their API has changed and that "view_only" isn't valid anymore, but that's what the documentation says to use.  I'm going to file a ticket to find out how to get it working.

Skytap Automation tools update

---

Rakefile

Version 2.0 of r10k requires ruby version >= 1.9.3. Until we have
a VM that supports this ruby version, we need to use r10k 1.5.1.
When a compatible ruby is available on the VM, we should return
to using a newer r10k version.

use r10k 1.5.1 for now

---

manifests/post.pp

This seemed better than duplicating all of the post build code in multiple node definitions.  At some point we should refactor all of this toward best practices, but I think it's fine for now.

Post selector

---

scripts/classroom/create_nodes.rb

Usage: create_nodes.rb [ list, of, nodenames, to, create | remove ]
This script will accept any number of nodenames on the commandline and will
run Puppet in a temporary ssldir for each nodename. This has the effect of
generating an arbitrary number of reports in the Console for screenshotting
purposes. For successful Puppet runs, it will also make a symlink so that
the Puppet Enterprise module can manage mco certificates.
* create_nodes.rb angelina barry craig wilson batman andrew corrine mandy
If you call it with the single argument of `remove` then it will crawl through
the real ssldir and remove all the nasty symlinks we left around.
* create_nodes.rb remove

Add janky script to make fake reports

---

scripts/classroom/setup_classroom.sh

This will eliminate the permission flap resulting from
https://tickets.puppetlabs.com/browse/PE-11356
Thanks for the rubber ducky from @acidprime and the original troubleshooting from @beergeek and @GeoffWilliams

(PE-11356) manage permissions properly

---

packer/scripts/student_build.sh
packer/scripts/training_build.sh

Centos6 ships with a really old version of ruby, which is starting to cause issues.  This updates to a newer version using RVM and will let us use other versions as needed.

Use RVM on Centos6 vms

---

packer/scripts/cleanup.sh

/etc/redhat-release is an easily modified and sometimes modified with file, because of older applications my company does modify this file.
It is arguable but one should not assume /etc/redhat-release is correct, only sure fire way is to look at uname output.
This method is reusable on RHEL7 as well where the contents of redhat-release change, just in case we have to update udev on RHEL7.
I tested on:
CentOS 6.5 and RHEL 6.5

Change method to determine OS release

---

Rakefile

This prevents a newer agent than ships with PE being installed.

Disable PC1 repo

---

Puppetfile
Rakefile
manifests/learning.pp
manifests/lms.pp
manifests/master.pp
manifests/student.pp
manifests/training.pp
packer/educationbase.json
packer/educationbuild.json
packer/learning.json
packer/master.json
packer/scripts/base.sh
packer/training.json

This goes with some changes to the bootstrap/learning modules to simplify and clean up.
Primarily it decouples the build from the hostname so that we could eventually build a Learning VM with the hostname "master.puppetlabs.vm".
It also adds a rake task for installing the learning VM on top of an existing master VM, which needs some more iteration.
Finally, it fixes the shutdown issue the learning VM build was having.

Simplify bootstrap

---

scripts/Rakefile
templates/pe.conf.erb

MEEP uses a pe.conf file instead of an answers file.  This adds a little logic to the Rakefile to do the right thing for each version.

2016.2 Installer conf file changes

---

templates/learning.json
templates/master.json
templates/openstackbuild.json
templates/training.json

I had accidentally removed the version number from too many places, so the output names for the builds were incorrect.

Output names

---

scripts/learning_cleanup.sh

Now that the pe module has been fixed this isn't needed.
Also removed the docker module install now that there's
an r10k method implemented.

remove second puppet run from learning_cleanup.sh

---

cloud/libvirt/courses/vms/master.xml.erb
cloud/libvirt/courses/volumes/master.xml.erb

Changes name to fqdn for dnsmasq to work correctly
Bumps up memory on master
Stops using .qcow2 for volume object names

Update libvirt templates

---

build_files/Puppetfile

When switching to pulling the classroom module from GH instead of
the Forge, make sure it's the correct URL. It could be corrected by
the user at the time they switch from the Forge to GH, but this
fix will make the Puppetfile internally consistent until then.

Fixed a consistency issue with a commented-out section of the file.

---

cloud/aws/courses/met.yaml

We don't want to distribute training.pem to the SDPs using the
MET, so a new keypair was created in the AWS Console just for
the MET.

Changed the name of the keypair used to log into MET VMs.

---

scripts/export-ova.sh

OSX uses the bsd version of sed, which was breaking on the jenkins build.  This also fixes the .mf file so that vmware doesn't complain.

Export ovas better

---

cloud/aws/courses/infrastructure.yaml

The `vcmanager` tool expects one machine to be in the `master` role, for indexing purposes. In ID, we don't have that. Each student is standalone. So instead, we'll stand one machine up just like the others that the instructor can use for demos and exercises, but we'll call it the `master`.

Add an instructor VM and call it `master`

---

Rakefile
scripts/docker_setup.sh
scripts/master_build.sh
templates/educationbuild.json
templates/educationtest.json

There are two things conflated here:
1. Updates the build scripts to output a single artifact that is both a valid .ova and a valid vagrant box. This means tests run with vagrant can be sure to catch issues with the OVA. It also will help us move to releasing a vagrant box if we choose to do that.
2. Generates a token for the deployer user at the end of the master build.  This will preempt the long boot times.

Single VM artifact and token

---

build_files/Rakefile
scripts/master_build.sh

This is mostly to support updating the local yumrepos and gem cache, but it should work with other changes as well.
The bit about the password is there because userprefs reset's the root password to "puppet" by default. I think we should fix that, but there might be people depending on it, so this is a compromise.

Add task to update existing VM

---

build_files/Puppetfile

The build currently uses the master branch of the pltraining modules.  This adds the option to use "release" which should be stable.
Modules which are published on the forge will be built with the stable version unless another is set and STABLE_MODULES is not enabled.
Releasable VM builds should be built with STABLE_MODULES=yes

Dynamic puppetfile

---

cloud/aws/userdata/default.erb

Goes with https://github.com/puppetlabs/vcmanager/pull/43
If the profile has a `master_ip` set, then this generates a cross platform `#cloud-config` userdata script. The way it works is slightly hacky, but should be solid. The `run-cmd` key applies directly to cloud-init, so it will be executed on the first boot. The `powershell` key is arbitrary, it's just there to make it valid YAML.
EC2Config (the windows service) reads the same file and looks for the `<powershell>` tags. Everything between those tags is evaluated as a PowerShell script on the first boot.

Adds a userdata template to go with vcmanager

---

cloud/aws/notes.erb

This is supposed to be captured and regurgitated in the `:notes` entry, but for some users it is not. Also, it seems like Learndot is stripping whitespace, so I added a whole bunch to validate that.

Add session url

---

cloud/skytap/PI.yaml
cloud/skytap/fundamentals.yaml
cloud/skytap/virtualclassroom.rb
cloud/skytap/windows.yaml

Windows VMs were defaulting to 2gb anyway, so this lets us use 2 cores
since it costs the same in skytap.

Set memory and cpus on student VMs on skytap.

---

Rakefile

The build was exiting 0 even when it failed. This causes it to actually fail on failures.

Properly fail if packer fails

---

cloud/skytap/PI.yaml
cloud/skytap/fundamentals.yaml
cloud/skytap/infrastructure.yaml
cloud/skytap/windows.yaml

Skytap templates need to be updated to use the 6.1 master and
training VMs.
New VM builds have been uploaded and saved as templates per
https://confluence.puppetlabs.com/display/EDU/How+to+set+up+Skytap
This change replaces the old template and VM ids for the master
and student VMs with the IDs of the new templates.

(TRAINTECH-1342) Update skytap templates for 6.1

---

templates/awsbuild.json

If we don't tag the instance as it is building, then the AWS Reaper will
indiscriminately murder it at some indeterminate time before it
completes. This allows it to live through completion.

(maint) Tag the building instance properly

---

cloud/skytap/PI.yaml
cloud/skytap/fundamentals.yaml
cloud/skytap/infrastructure.yaml
cloud/skytap/windows.yaml

Update the skytap templates to use the template and VM IDs
of the newly-uploaded 6.2 master and training VMs in Skytap.
Reviewer should validate changes against
https://cloud.skytap.com/templates

(MAINT) Update skytap templates to 6.2 VMs

---

build_files/Puppetfile

Modify the build_files/Puppetfile to use the legacy branch of the
pltraining-bootstrap repository for builds until we can switch entirely
to the new build process implemented in the master branch of that
repository. This will allow us to continue using existing Jenkins build
pipelines unless/until those are adapted and tested against the new
build process.

(MAINT) Use legacy branch of pltrainign-bootstrap

---

build_files/Puppetfile

We need to add the sudo dependency to support: https://github.com/puppetlabs/pltraining-bootstrap/commit/218f994b66dbef56166a6238af533cc1b2c99349

(MAINT) Add saz/sudo dependency to Puppetfile

---

cloud/skytap/virtualclassroom.rb

This prints a warning to STDERR. This means that you can still redirect output to a file and the warning will still display on the console without corrupting the file.

(maint) Display a warning about auto suspend

---

build_files/Rakefile

This fixed a regression I believe was introduced in
https://github.com/puppetlabs/education-builds/pull/830 that skipped
deleting the /tmp directory in the cleanup step. This added about 0.5GB
to the final OVA size.

(MAINT) Delete the /tmp directory in cleanup

---

cloud/aws/codes.yaml

Added missing codes for PI ILT classes. Still need to temporarily modify
the course name in Learndot so vcmanager starts the instances in the
correct virtual classroom, e.g. linked to one of the three Guacamole instances.

(maint) Add PI class codes for ILT courses

---

build_files/Puppetfile.learning
build_files/Rakefile

Put the learning vm persistent modules used to support the quest tool in
the /etc/puppetlabs/code/modules directory rather than production
environment modules directory so that they won't be overwritten by
deploys done in the control-repo quest.

LEARNVM-624 Put peristent modules in non-env dir

---

cloud/aws/notes.erb

The released version of `vcmanager` doesn't have trim enabled, so this breaks hard.

(maint) Remove trim modifier

---

cloud/aws/userdata/default.erb

The Windows default hosts file doesn't appear to end with a newline, so let's add one.
TRAINTECH-1599 #resolved #time 10m

Add newline to hosts file

---

cloud/aws/courses/met.yaml

Also add a `description` key to the yaml file to help future updates.
This should not affect any tooling, as we don't use that key for
anything.
Note that this drops the requirement specificity from eg "CentOS 7.2" to "CentOS 7.x". This is so we can use the official instance. Flag if that's not acceptable.
SDPONBOARD-150 #resolved #time 90m

Update MET AMIs to HVM
